config/routes.rb
require 'sidekiq/web'
require 'sidekiq-cron'

Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  root 'characters#root_index'

  resources :characters do
    member do
    end
    collection do
      get 'date/:month/:day' => 'characters#date'
    end
  end

  resources :welcome do
    collection do
      get :about
      get :support
    end
  end

  post 'favorites/:character_id/' => 'favorites#toggle'

  resources :manage do
    collection do
      post :tweet_character_birthday
    end
  end

end

app/models/character.rb
# coding: utf-8
# == Schema Information
#
# Table name: characters
#
#  id               :integer          not null, primary key
#  slug             :string
#  name_en          :string
#  name_ko          :string
#  name_jp          :string
#  year             :integer
#  date             :string(5)
#  external_url     :string           default("")
#  anime_db_id      :integer
#  anime_db_img_url :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  source_id        :integer
#


require 'date'

class Character < ActiveRecord::Base
  include CharactersHelper
  include FavoritesHelper

  rails_admin do
  end

  has_many :favorite

  validates :slug, uniqueness: true
  validates :date, length: { is: 5 }
  validates :date, format: { with: /\d\d\/\d\d/ }

  def month
    extract_month_from_str date
  end

  def day
    extract_day_from_str date
  end

  def birthday_to_s
    if year
      "#{year}년 #{month}월 #{day}일"
    else
      "#{month}월 #{day}일"
    end
  end

  def birthday year
    Date.new(year, month, day)
  end

  def curr_birthday
    birthday Date.today.year
  end

  def next_birthday today
    curr_year = today.year
    curr_year_birthday = birthday curr_year
    next_year_birthday = birthday curr_year + 1

    if curr_year_birthday < today
      return next_year_birthday
    else
      return curr_year_birthday
    end
  end


  def remain_days(date = nil)
    date = Date.today if date.nil?

    next_day = next_birthday date
    next_day.mjd - date.mjd
  end

  def d_day(date = nil)
    date = Date.today if date.nil?

    remain = remain_days date
    if remain == 0
      "D-Day"
    else
      "D-#{remain}"
    end
  end

  def anime_character_db_url
    "http://www.animecharactersdatabase.com/character.php?id=#{anime_db_id}"
  end
end

app/controllers/character_controller.rb
require 'date'

class CharacterController < ApplicationController
  before_action :assign_month_day

  def assign_month_day
    today = Date.today
    @month = (params.has_key? :month) ? params[:month].to_i : today.month
    @day = (params.has_key? :day) ? params[:day].to_i : today.day
  end

  def index
    @today_list = get_today_character_list @month, @day
    @next_list = get_next_character_list @month, @day
    approach_count = 3
    @approach_list = @next_list[0...approach_count]
  end

  def date
    @character_list = get_today_character_list @month, @day
  end

  def detail
    @slug = params[:slug]
    @character = Character.find_by slug: @slug
  end

  def list
    today_list = get_today_character_list @month, @day
    next_list = get_next_character_list @month, @day
    @all_list = today_list + next_list
  end

  def get_today_character_list(month, day)
    date_str = Character.date_to_s month, day
    today_q = Character.where(date: date_str)
    today_list = today_q.to_a
  end

  def get_next_character_list(month, day)
    date_str = Character.date_to_s month, day
    # today ~ year end
    curr_year_q = Character.where('date > ?', date_str).order(date: :asc)
    # year start ~ today
    next_year_q = Character.where('date < ?', date_str).order(date: :asc)
    next_list = curr_year_q.to_a + next_year_q.to_a
  end
end

app/controllers/characters_controller.rb
require 'date'

class CharactersController < ApplicationController
  def date
    @character_list = get_today_character_list @month, @day
  end

  def index
    today_str = Character.date_to_s @month, @day

    # today ~ year end
    curr_year_q = Character.where('date >= ?', today_str).order(date: :asc)
    # year start ~ today
    next_year_q = Character.where('date < ?', today_str).order(date: :asc)
    curr_year_list = curr_year_q.to_a
    next_year_list = next_year_q.to_a
    @all_list = curr_year_list + next_year_list

    # TODO 월별로 정렬하기. 남은것과 지난것을 따로 처리하기
    @month_table = {}
    (@month...(@month + 13)).each do |m|
      @month_table[m] = []
    end
    curr_year_list.each do |character|
      month = character.month
      @month_table[month] << character
    end
    next_year_list.each do |character|
      month = character.month + 12
      @month_table[month] << character
    end
    @month_table = @month_table.select { |k, v| v.length > 0 }
  end

  def show
    @character = Character.find_by(id: params[:id])
    return render :status => 404 if @character.nil?

    favorite_user_q = @character.user_list_q
    @favorite_count = favorite_user_q.count

    if user_signed_in?
      @favorite = Favorite.find_by(user: current_user, character: @character)
    else
      @favorite = nil
    end
  end

  def root_index
    @today_list = get_today_character_list @month, @day
    @tomorrow_list = get_today_character_list @tomorrow_month, @tomorrow_day

    @next_list = get_next_character_list
    approach_count = 3
    @approach_list = @next_list[0...approach_count]
  end

  def get_today_character_list(month, day)
    date_str = Character.date_to_s month, day
    today_q = Character.where(date: date_str)
    today_list = today_q.to_a
  end

  def get_next_character_list
    today_str = Character.date_to_s @month, @day
    tomorrow_str = Character.date_to_s @tomorrow_month, @tomorrow_day

    # tomorrow ~ year end
    curr_year_q = Character.where('date > ?', tomorrow_str).order(date: :asc)
    # year start ~ today
    next_year_q = Character.where('date < ?', today_str).order(date: :asc)
    next_list = curr_year_q.to_a + next_year_q.to_a
  end
end

app/helpers/character_helper.rb
module CharacterHelper
  def self.included(base)
    base.extend(ClassMethods)
  end

  module ClassMethods
    def date_to_s(month, day)
      return nil if month > 12
      return nil if month < 1
      return nil if day > 31
      return nil if day < 1

      Kernel::sprintf("%02d/%02d", month, day)
    end
  end

  def str_to_date(val)
    {month: extract_month_from_str(val), day: extract_day_from_str(val)}
  end

  def extract_month_from_str(val)
    month = val[0...2].to_i
  end

  def extract_day_from_str(val)
    return nil if val.length != 5
    day = val[3...5].to_i
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def self.included(base)
    base.extend(ClassMethods)
  end

  module ClassMethods
    def date_to_s(month, day)
      return nil if month > 12
      return nil if month < 1
      return nil if day > 31
      return nil if day < 1

      Kernel::sprintf("%02d/%02d", month, day)
    end
  end

  def str_to_date(val)
    {month: extract_month_from_str(val), day: extract_day_from_str(val)}
  end

  def extract_month_from_str(val)
    month = val[0...2].to_i
  end

  def extract_day_from_str(val)
    return nil if val.length != 5
    day = val[3...5].to_i
  end
end

app/views/characters/_d_day.html.erb
<%# 생일에 근접할수록 색이 달라지면 재밌을거다 %>
<% if character.remain_days(date) == 0 %>
  <button class="button small danger"><%= character.d_day date %></button>
<% elsif character.remain_days(date) == 1 %>
  <button class="button small warning"><%= character.d_day date %></button>
<% elsif character.remain_days(date) <= 7 %>
  <button class="button small success"><%= character.d_day date %></button>
<% elsif character.remain_days(date) <= 28 %>
  <button class="button small info"><%= character.d_day date %></button>
<% else %>
  <button class="button small"><%= character.d_day date %></button>
<% end %>

app/views/characters/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'happybirthdaywaifu'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/characters/_simple_tile.html.erb
<div class="tile tile-wide-x bg-cyan" data-click="transform" data-role="tile">
  <%= link_to character_path(character.id) do %>
    <div class="tile-content tile-content-character fg-white">
      <img src="/static/thumb/<%= character.anime_db_id %>.jpg">
      <div class="data-wrapper">
        <span class="data-title"><%= character.name_ko %></span>
        <span class="data-text"><%= character.name_jp %></span>
        <span class="data-text"><%= character.name_en %></span>
        <span class="data-subtitle"><%= character.birthday_to_s %></span>
      </div>
      <span class="tile-badge bg-darkRed"><%= character.d_day date %></span>
    </div>
  <% end %>
</div>

app/views/characters/_twitter_card.html.erb
<% unless character.nil? %>
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@birth_bot_waifu">
<meta name="twitter:creator" content="@birth_bot_waifu">
<meta name="twitter:title" content="<%= character.name_ko %> 생일">
<meta name="twitter:description" content="<%=character.birthday_to_s%>은 <%=character.name_ko%>(<%=character.name_jp%>, <%=character.name_en%>) 생일입니다. http://birthday.libsora.so/characters/<%=character.id %>">
<meta name="twitter:image:src" content="<%=character.anime_db_img_url %>">
<% end %>

app/views/characters/date.html.erb
<div id="birthday-calendar" data-role="calendar"
  data-day-click="dayClick" data-date="<%= @today_str %>"></div>


<h2><time><%= @month %>월 <%= @day %>일</time></h2>
<section class="clearfix">
  <% @character_list.each do |character| %>
    <%= render 'simple_tile', character: character, date: @today %>
	<% end %>
</section>

app/views/characters/index.html.erb
<!-- calendar -->
<div id="birthday-calendar" data-role="calendar"
  data-day-click="dayClick" data-date="<%= @today_str %>"></div>

<div>
  <% @month_table.each do |month, character_list| %>
    <div class="panel">
      <div class="heading">
        <span class="title"><%= month % 12 == 0 ? 12 : month % 12 %>월</span>
      </div>
      <div class="content">
        <ul class="unstyled">
          <% character_list.each do |character| %>
            <li class="character-list-elem">
              <span class="birthday-text">
                <%= character.birthday_to_s %>
              </span>

              <%= link_to character_path(character.id) do %>

                <span class="d-day-text">
                  <%= render 'characters/d_day', character: character, date: @today %>
                </span>

                <%= character.name_ko %> |
                <%= character.name_en %> |
                <%= character.name_jp %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/characters/root_index.html.erb
<h2>
  <small>
    <% waifu_url ="http://rigvedawiki.net/r1/wiki.php/%EB%8A%94%20%EB%82%98%EC%9D%98%20%EC%8B%A0%EB%B6%80" %>
	  <a href="<%= waifu_url %>">신부</a>의 생일을 잊어서 이벤트를 준비하지 못하셨나요?
    기념일을 까먹어서 nice boat가 일어날거 같다구요?
    걱정 마세요.
    Happy Birthday, Waifu 를 이용해서 신부의 생일을 기억하세요.
    그리고 가족, 친구와 같이 신부의 생일을 축하해주세요.
  </small>
</h2>
<%= link_to about_welcome_index_path, class: "button bg-darkRed bg-hover-red fg-white large" do %>
	자세히 &raquo;
<% end %>

<% if @today_list.length > 0 %>
  <section class="clearfix">
	  <h2>오늘(<time><%= @month %>월 <%= @day %>일</time>)</h2>
	  <% @today_list.each do |character| %>
      <%= render 'simple_tile', character: character, date: @today %>
	  <% end %>
  </section>
<% end %>

<% if @tomorrow_list.length > 0 %>
  <section class="clearfix">
	  <h2>내일(<time><%= @tomorrow_month %>월 <%= @tomorrow_day %>일</time>)</h2>
	  <% @tomorrow_list.each do |character| %>
      <%= render 'simple_tile', character: character, date: @today %>
	  <% end %>
  </section>
<% end %>

<% if @approach_list %>
  <section class="clearfix">
	  <h2>Coming soon</h2>
	  <% @approach_list.each do |character| %>
      <%= render 'simple_tile', character: character, date: @today %>
	  <% end %>
  </section>
<% end %>


<section>
  <%= render_shareable :turbolinks => true,
  :buttons => ['twitter', 'google_plus', 'tumblr', 'facebook'],
  :facebook => {:turbolinks => false} %>
</section>

<br/>

app/views/characters/show.html.erb
<h2><%= @character.name_ko %></h2>
<dl class>
  <dt>Name</dt>
  <dd><%= @character.name_en %></dd>
  <dt>名前</dt>
  <dd><%= @character.name_jp %></dd>
  <dt>이름</dt>
  <dd><%= @character.name_ko %></dd>
  <dt>생일</dt>
  <dd><%= @character.birthday_to_s %></dd>
  <dt>D-Day</dt>
  <dd><%= render 'd_day', character: @character, date: @today %><dd>
</dl>

<% if @character.anime_db_img_url %>
  <img src="<%= @character.anime_db_img_url %>"
	  class="img-responsive"/>
<% end %>

<!--
<h2>Favorite / Notification</h2>
<p><%= @favorite_count %>명의 노답인생이 캐릭터의 생일을 축하할 예정입니다.</p>
<% if not user_signed_in? %>
  <div class="alert alert-warning" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    Twitter 로그인을 하면 생일 알림을 사용할 수 있습니다.
  </div>
<% else %>

  <% if @favorite %>
    <form method="post"
	    action="<%= url_for controller: 'favorites', action: 'toggle', character_id: @character.id %>">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      <button type="submit" class="btn btn-primary">알림 해제</button>
    </form>
  <% else %>
    <form method="post"
	    action="<%= url_for controller: 'favorites', action: 'toggle', character_id: @character.id %>">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      <button type="submit" class="btn btn-default">알림 등록</button>
    </form>
  <% end %>

<% end %>
-->

<h2>External Link</h2>
<ul>
  <% if !@character.external_url.empty? %>
    <li>
	    <%= link_to "외부 링크", @character.external_url %>
    </li>
  <% end %>
  <li>
	  <%= link_to "Anime Characters Database", @character.anime_character_db_url %>
  </li>
</ul>

<section>
  <%= render_shareable :turbolinks => true,
  :buttons => ['twitter', 'google_plus', 'tumblr', 'facebook'],
  :facebook => {:turbolinks => false} %>
</section>

<%= render 'disqus' %>