config/routes.rb
require 'sidekiq/web'
require 'sidekiq-cron'

Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  root 'characters#root_index'

  resources :characters do
    member do
    end
    collection do
      get 'date/:month/:day' => 'characters#date'
    end
  end

  resources :welcome do
    collection do
      get :about
      get :support
    end
  end

  post 'favorites/:character_id/' => 'favorites#toggle'

  resources :manage do
    collection do
      post :tweet_character_birthday
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="if1live">

    <%= render '/characters/twitter_card', character: @character %>


    <title>Happy Birthday, Waifu</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
	    <!-- menu -->
      <div class="app-bar" data-role="appbar">
        <a class="app-bar-element branding" href="/">Happy Birthday, Waifu</a>
        <ul class="app-bar-menu">
          <li><%= link_to "All", characters_path %></li>
          <li><%= link_to "Help", support_welcome_index_path %></li>

          <!-- disable login
          <% if user_signed_in? %>
		        <li>
              <%= link_to controller: "users", action: "show" do %>
			          <i class="icon-twitter"> </i> <%= current_user.name %>
			        <% end %>
            </li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete,
			        data: { confirm: "로그아웃하시겠습니까?" } %>
            </li>
		      <% else %>
		        <li>
			        <%= link_to user_omniauth_authorize_path(:twitter) do %>
			          <i class="icon-twitter"> </i> Login
			        <% end %>
            </li>
		      <% end %>
          -->
        </ul>
      </div>
	    <!-- // menu -->

	    <%= yield %>

      <!-- footer -->
      <hr/>
	    <footer>
        <p>
          &copy; 2015 Happy Birtday, Waifu
          |
		      <a href="https://twitter.com/waifu_birth_bot">@waifu_birth_bot</a>
          |
          <a href="https://twitter.com/if1live">@if1live</a>
          |
		      <a href="https://github.com/if1live/happy-birthday-waifu">Repository</a>
        </ul>
      </footer>
    </div>

    <script>
      var TODAY = new Date("<%= @today_str %>");
      var TOMORROW = new Date("<%= @tomorrow_str %>");
      var YESTERDAY = new Date("<%= @yesterday_str %>");
    </script>

    <!-- lazy js loading -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- GA -->
    <script>
	   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	                            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	   ga('create', 'UA-43577716-5', 'auto');
	   ga('send', 'pageview');
    </script>

    <!-- notify -->
    <script>
     <% if notice %>
     (function(){
	     var not = $.Notify({
	       caption: "Authorization",
	       content: "<%= notice %>",
	       timeout: 10000 // 10 seconds
	     });
     })();
     <% end %>
    </script>
    <!-- // notify -->
  </body>
</html>